### ISSUE TITLE
Fresh install erroring with uninitialized constant CircleCi::Response::Forwardable (NameError)

### ISSUE THREAD

**Issue by Ramblurr** [circle-cli/circle-cli#23]
Just installed from rubygems, and the tool isn't working.

For any command it errors out with: 

```
/Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci/response.rb:7:in `<class:Response>': uninitialized constant CircleCi::Response::Forwardable (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci/response.rb:6:in `<module:CircleCi>'
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci/response.rb:2:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci.rb:16:in `require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci.rb:16:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci.rb:16:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/circleci-1.0.2/lib/circleci.rb:16:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.1.1/lib/circle/cli/project.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.1.1/lib/circle/cli/app.rb:3:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.1.1/lib/circle/cli.rb:3:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.1.1/lib/circle-cli.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/circle-cli-0.1.1/bin/circle:3:in `<top (required)>'
    from /usr/local/bin/circle:23:in `load'
    from /usr/local/bin/circle:23:in `<main>'
```

**Comment by codeurge** [comment]
This issue was also reported in #21, this is an issue on the CircleCI gem and a PR has been opened by @rzane https://github.com/mtchavez/circleci/pull/82

**Comment by codeurge** [comment]
@Ramblurr I believe this issue is now resolved with the new version of the CircleCI gem.
